INSERT INTO degree (degree, created_at) values
('Ambiental',curdate()),
('Automotriz',curdate()),
('Energías Renovables',curdate()),
('Gastronomía',curdate()),
('Ingeniería Industrial',curdate()),
('Matenimiento',curdate()),
('Mecatrónica',curdate()),
('Negocios',curdate()),
('Tecnologías de la Información',curdate());

INSERT INTO specialization (specialization, degree_id, created_at) VALUES
('Desarrollo de software en Multiplataforma',9,curdate()),
('Infraestructura en Redes Digitales',9,curdate());

INSERT INTO teacher (teacher_name, last_name,mother_last_name,date_of_birth,email,phone,teacher_status,professional_license,created_at) VALUES
('Jose David','Urquieta','Alanis','1985-01-01','alanis@profesor.utpuebla.edu.mx','22222222',1,'',curdate()),
('Guillermo','Flores','Sanchez','1985-01-01','memo@profesor.utpuebla.edu.mx','22222222',1,'',curdate()),
('Arturo','Lopez','Rojas','1985-01-01','arturo@profesor.utpuebla.edu.mx','22222222',1,'',curdate()),
('Hilda','Matias','Mejia','1985-01-01','Hilda@profesor.utpuebla.edu.mx','22222222',1,'',curdate()),
('Pedro','Galaviz','Martinez','1985-01-01','Pedro@profesor.utpuebla.edu.mx','22222222',1,'',curdate()),
('Teresa','Trejo','Ramirez','1985-01-01','Teresa@profesor.utpuebla.edu.mx','22222222',1,'',curdate()),
('Yrut','Rodriguez','Lopez','1985-01-01','Yrut@profesor.utpuebla.edu.mx','22222222',1,'',curdate()),
('Aurora Rosa','Palacios','Lopez','1985-01-01','Aurora@profesor.utpuebla.edu.mx','22222222',1,'',curdate());

INSERT INTO period (start_month, end_month, created_at) VALUES
('Enero','Abril',curdate()),
('Mayo','Agosto',curdate()),
('Septiembre','Diciembre',curdate());

INSERT INTO four_month_period (fmp_number, period_id, created_at) VALUES
(1,3,curdate()),
(2,1,curdate()),
(3,2,curdate()),
(4,3,curdate()),
(5,1,curdate()),
(6,2,curdate()),
(7,3,curdate()),
(8,1,curdate()),
(9,2,curdate()),
(10,3,curdate()),
(11,1,curdate());

INSERT INTO subjectutp (subjectutp, fmp_id, created_at) VALUES
('Administracion de BD',8,curdate()),
('Desarrollo web profesional',8,curdate()),
('Ingles VII',8,curdate()),
('Matematicas para Ingenieria II',8,curdate()),
('Planeacion y organizacion del trabajo',8,curdate()),
('Seguridad en el Desarrollo de Aplicaciones',8,curdate()),
('Compúto en la nube',8,curdate()),
('Dirección de Proyecto I',8,curdate()),
('Gestión de la seguridad informática',8,curdate()),
('Matematicas para Ingenieria I',8,curdate());

INSERT INTO specialization_subject (specialization_id, subject_id, created_at) values
(1,1,curdate()),
(1,2,curdate()),
(1,3,curdate()),
(1,4,curdate()),
(1,5,curdate()),
(1,6,curdate()),
(2,3,curdate()),
(2,5,curdate()),
(2,7,curdate()),
(2,8,curdate()),
(2,9,curdate()),
(2,10,curdate());

INSERT INTO teacher_subject (teacher_id, subjectutp_id, created_at) VALUES
(1,6,curdate()),
(1,9,curdate()),
(4,1,curdate()),
(5,2,curdate()),
(6,3,curdate()),
(7,4,curdate()),
(8,5,curdate());

INSERT INTO teacher_specialization (specialization_id, teacher_id) VALUES
(1,1),
(1,2),
(1,3),
(1,4),
(1,5),
(1,6),
(1,7),
(1,8),
(2,1);

INSERT INTO letter (letter, created_at) VALUES
('A',curdate()),
('B',curdate()),
('C',curdate()),
('D',curdate()),
('E',curdate()),
('F',curdate()),
('G',curdate()),
('H',curdate()),
('I',curdate());

INSERT INTO grouputp (fmp_id, letter_id, shift, created_at) VALUES
(1,1,'Matutino',curdate()),
(1,2,'Matutino',curdate()),
(1,3,'Matutino',curdate()),
(1,4,'Matutino',curdate()),
(1,5,'Matutino',curdate()),
(1,6,'Matutino',curdate()),
(1,7,'Matutino',curdate()),
(1,8,'Matutino',curdate()),
(1,9,'Matutino',curdate()),
(2,1,'Matutino',curdate()),
(2,2,'Matutino',curdate()),
(2,3,'Matutino',curdate()),
(2,4,'Matutino',curdate()),
(2,5,'Matutino',curdate()),
(2,6,'Matutino',curdate()),
(2,7,'Matutino',curdate()),
(2,8,'Matutino',curdate()),
(2,9,'Matutino',curdate()),
(3,1,'Matutino',curdate()),
(3,2,'Matutino',curdate()),
(3,3,'Matutino',curdate()),
(3,4,'Matutino',curdate()),
(3,5,'Matutino',curdate()),
(3,6,'Matutino',curdate()),
(3,7,'Matutino',curdate()),
(3,8,'Matutino',curdate()),
(3,9,'Matutino',curdate()),
(4,1,'Matutino',curdate()),
(4,2,'Matutino',curdate()),
(4,3,'Matutino',curdate()),
(4,4,'Matutino',curdate()),
(4,5,'Matutino',curdate()),
(4,6,'Matutino',curdate()),
(4,7,'Matutino',curdate()),
(4,8,'Matutino',curdate()),
(4,9,'Matutino',curdate()),
(5,1,'Matutino',curdate()),
(5,2,'Matutino',curdate()),
(5,3,'Matutino',curdate()),
(5,4,'Matutino',curdate()),
(5,5,'Matutino',curdate()),
(5,6,'Matutino',curdate()),
(5,7,'Matutino',curdate()),
(5,8,'Matutino',curdate()),
(5,9,'Matutino',curdate()),
(6,1,'Matutino',curdate()),
(6,2,'Matutino',curdate()),
(6,3,'Matutino',curdate()),
(6,4,'Matutino',curdate()),
(6,5,'Matutino',curdate()),
(6,6,'Matutino',curdate()),
(6,7,'Matutino',curdate()),
(6,8,'Matutino',curdate()),
(6,9,'Matutino',curdate()),
(7,1,'Vespertino',curdate()),
(7,2,'Vespertino',curdate()),
(7,3,'Vespertino',curdate()),
(7,4,'Vespertino',curdate()),
(7,5,'Vespertino',curdate()),
(7,6,'Vespertino',curdate()),
(7,7,'Vespertino',curdate()),
(7,8,'Vespertino',curdate()),
(7,9,'Vespertino',curdate()),
(8,1,'Vespertino',curdate()),
(8,2,'Vespertino',curdate()),
(8,3,'Vespertino',curdate()),
(8,4,'Vespertino',curdate()),
(8,5,'Vespertino',curdate()),
(8,6,'Vespertino',curdate()),
(8,7,'Vespertino',curdate()),
(8,8,'Vespertino',curdate()),
(8,9,'Vespertino',curdate()),
(9,1,'Vespertino',curdate()),
(9,2,'Vespertino',curdate()),
(9,3,'Vespertino',curdate()),
(9,4,'Vespertino',curdate()),
(9,5,'Vespertino',curdate()),
(9,6,'Vespertino',curdate()),
(9,7,'Vespertino',curdate()),
(9,8,'Vespertino',curdate()),
(9,9,'Vespertino',curdate()),
(10,1,'Vespertino',curdate()),
(10,2,'Vespertino',curdate()),
(10,3,'Vespertino',curdate()),
(10,4,'Vespertino',curdate()),
(10,5,'Vespertino',curdate()),
(10,6,'Vespertino',curdate()),
(10,7,'Vespertino',curdate()),
(10,8,'Vespertino',curdate()),
(10,9,'Vespertino',curdate()),
(11,1,'Vespertino',curdate()),
(11,2,'Vespertino',curdate()),
(11,3,'Vespertino',curdate()),
(11,4,'Vespertino',curdate()),
(11,5,'Vespertino',curdate()),
(11,6,'Vespertino',curdate()),
(11,7,'Vespertino',curdate()),
(11,8,'Vespertino',curdate()),
(11,9,'Vespertino',curdate());
